[linux]
rhel-control ansible_host=192.0.2.10 ansible_user=ansible
alpine-api ansible_host=192.0.2.11 ansible_user=ansible
arch-observe ansible_host=192.0.2.12 ansible_user=ansible
suse-auth ansible_host=192.0.2.13 ansible_user=ansible
debian-db ansible_host=192.0.2.14 ansible_user=ansible

[app]
alpine-api

[observability]
arch-observe

[auth]
suse-auth

[database]
debian-db
