/**
 * The Slack adapter.
 *
 * `fetch` refreshes the pinned snapshot from Slack's documentation and the
 * recorded samples in `slackapi/java-slack-sdk`. `extract` and `build` arrive
 * with the later stages of the pipeline.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { relative } from 'node:path'
import process from 'node:process'

import type { Adapter, BuildOptions } from '../registry.ts'
import type { ApiModel } from '../../core/model.ts'
import { collectWarnings } from '../../core/model.ts'
import { emitOpenApi } from '../../core/emit.ts'
import { fetchAllBytes, fetchText } from '../../core/http.ts'
import { loadConfig } from '../../core/config.ts'
import { pruneSample } from '../../core/prune.ts'
import { Snapshot, SnapshotWriter } from '../../core/snapshot.ts'
import { extractApiModel } from './extract.ts'
import {
  joinIndexes,
  parseMethodIndex,
  parseSampleIndex,
  SAMPLE_INDEX_URL,
  selectScope,
  SITEMAP_URL,
  type DiscoveredMethod,
} from './discover.ts'

export const SLACK_ADAPTER: Adapter = {
  name: 'slack',
  fetch: fetchSnapshot,
  extract: extractFromSnapshot,
  build: buildDescriptor,
}

async function extractFromSnapshot(): Promise<ApiModel> {
  const config = await loadConfig('slack')
  return extractApiModel(config, await Snapshot.open(config.snapshotDir))
}

/**
 * Regenerate the descriptor from the snapshot.
 *
 * `info.version` is the snapshot's fetch date, so the descriptor states how
 * current its inputs are and changes only when they do.
 */
async function buildDescriptor(options: BuildOptions): Promise<boolean> {
  const config = await loadConfig('slack')
  const snapshot = await Snapshot.open(config.snapshotDir)
  const model = await extractApiModel(config, snapshot)

  const warnings = collectWarnings(model)
  for (const warning of warnings) {
    log(`warning: ${warning}`)
  }

  const yaml = emitOpenApi(model, { version: snapshot.fetchedAt.slice(0, 'YYYY-MM-DD'.length) })
  const banner =
    '# Generated by tools/openapi-forge. Do not edit.\n' +
    '#\n' +
    '# Regenerate with `make slack-spec`. Corrections belong in\n' +
    '# tools/openapi-forge/apis/slack/overlay.yaml, not here.\n'
  const contents = banner + yaml

  if (options.check) {
    const current = await readFile(config.outputPath, 'utf8').catch(() => undefined)
    if (current === contents) {
      log(`${relative(process.cwd(), config.outputPath)} is up to date`)
      return true
    }
    log(
      `${relative(process.cwd(), config.outputPath)} is stale; ` +
        `re-run without --check to regenerate`,
    )
    return false
  }

  await writeFile(config.outputPath, contents)
  log(
    `wrote ${relative(process.cwd(), config.outputPath)} ` +
      `(${model.operations.length} operations, ${warnings.length} warnings)`,
  )
  return true
}

export function docsPath(method: DiscoveredMethod): string {
  return `docs/${method.slug}.md`
}

export function samplePath(method: DiscoveredMethod): string {
  return `samples/${method.name}.json`
}

function log(message: string): void {
  process.stderr.write(`${message}\n`)
}

async function fetchSnapshot(): Promise<void> {
  const config = await loadConfig('slack')

  log('fetching indexes')
  const [sitemap, sampleIndex] = await Promise.all([
    fetchText(SITEMAP_URL),
    fetchText(SAMPLE_INDEX_URL),
  ])
  const { methods, samplesWithoutDocs } = joinIndexes(
    parseMethodIndex(sitemap),
    parseSampleIndex(sampleIndex),
  )
  log(`  ${methods.length} documented methods, ${samplesWithoutDocs.length} samples without docs`)

  const { selected, missing } = selectScope(methods, config.methods)
  if (missing.length > 0) {
    throw new Error(
      `configured methods are no longer documented by Slack: ${missing.join(', ')}. ` +
        `Remove them from apis/slack/config.yaml, or check whether they were renamed.`,
    )
  }
  const undocumented = methods.length - config.methods.length
  log(`  ${selected.length} in scope, ${undocumented} documented methods out of scope`)

  const urls = selected.flatMap((method) =>
    method.sampleUrl === undefined ? [method.docsUrl] : [method.docsUrl, method.sampleUrl],
  )
  log(`downloading ${urls.length} files`)
  const bodies = await fetchAllBytes(urls)

  const writer = new SnapshotWriter(config.snapshotDir)
  let sampleBytes = 0
  let prunedBytes = 0
  for (const method of selected) {
    const docs = bodies.get(method.docsUrl)
    if (docs === undefined) {
      throw new Error(`no response for ${method.docsUrl}`)
    }
    writer.add(docsPath(method), method.docsUrl, docs, new TextDecoder().decode(docs))

    if (method.sampleUrl === undefined) {
      log(`  ${method.name}: no recorded response sample`)
      continue
    }
    const sample = bodies.get(method.sampleUrl)
    if (sample === undefined) {
      throw new Error(`no response for ${method.sampleUrl}`)
    }
    // Samples are stored pruned: the raw ones run to megabytes of Block Kit
    // nesting that no Coral column ever reads. The manifest still pins the
    // digest of the raw bytes, so upstream changes remain detectable.
    const pruned = `${JSON.stringify(
      pruneSample(JSON.parse(new TextDecoder().decode(sample))),
      undefined,
      2,
    )}\n`
    sampleBytes += sample.length
    prunedBytes += pruned.length
    writer.add(samplePath(method), method.sampleUrl, sample, pruned)
  }

  const manifest = await writer.commit(new Date().toISOString())
  log(
    `wrote ${manifest.inputs.length} inputs to apis/slack/snapshot ` +
      `(samples pruned ${formatBytes(sampleBytes)} to ${formatBytes(prunedBytes)})`,
  )
}

function formatBytes(bytes: number): string {
  return bytes < 1024 * 1024
    ? `${Math.round(bytes / 1024)} KB`
    : `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
