line_ending: lf
doublestar: true

include:
  - sources/*/manifest.yaml

formatter:
  type: basic
  indent: 2
  include_document_start: false
  max_line_length: 120
  trim_trailing_whitespace: true
  eof_newline: true
  pad_line_comments: 2
  retain_line_breaks_single: true
