events {}

http {
  server {
    listen 443 ssl;
    http2 on;
    ssl_certificate /tls/cert.pem;
    ssl_certificate_key /tls/key.pem;

    location / {
      grpc_pass grpc://coral:14555;
    }
  }
}
