//! Registry of diagnostic code constants emitted by virtual-graph validation;
//! each const's name equals its string value.
#![allow(
    unreachable_pub,
    reason = "The registry intentionally keeps uniform pub const declarations inside the virtual graph module."
)]

pub const AMBIGUOUS_RELATIONSHIP_MAPPING: &str = "AMBIGUOUS_RELATIONSHIP_MAPPING";
pub const CYPHER_PARSE_ERROR: &str = "CYPHER_PARSE_ERROR";
pub const DISCONNECTED_PATTERN: &str = "DISCONNECTED_PATTERN";
pub const DUPLICATE_NODE_LABEL: &str = "DUPLICATE_NODE_LABEL";
pub const DUPLICATE_OPTIONAL_RELATIONSHIP: &str = "DUPLICATE_OPTIONAL_RELATIONSHIP";
pub const DUPLICATE_RELATIONSHIP_MAPPING: &str = "DUPLICATE_RELATIONSHIP_MAPPING";
pub const DUPLICATE_VARIABLE: &str = "DUPLICATE_VARIABLE";
pub const EMPTY_FIELD: &str = "EMPTY_FIELD";
pub const EMPTY_NODES: &str = "EMPTY_NODES";
pub const EMPTY_PLAN: &str = "EMPTY_PLAN";
pub const EMPTY_PROJECTION: &str = "EMPTY_PROJECTION";
pub const EMPTY_VARIABLE: &str = "EMPTY_VARIABLE";
pub const GRAPHQL_PARSE_ERROR: &str = "GRAPHQL_PARSE_ERROR";
pub const INVALID_AGGREGATE_TARGET: &str = "INVALID_AGGREGATE_TARGET";
pub const INVALID_ELEMENT_ID_PROJECTION: &str = "INVALID_ELEMENT_ID_PROJECTION";
pub const INVALID_ENDPOINT_VARIABLE: &str = "INVALID_ENDPOINT_VARIABLE";
pub const INVALID_GRAPH_IDENTITY_PROJECTION: &str = "INVALID_GRAPH_IDENTITY_PROJECTION";
pub const INVALID_KEY_PROJECTION: &str = "INVALID_KEY_PROJECTION";
pub const INVALID_LABELS_PROJECTION: &str = "INVALID_LABELS_PROJECTION";
pub const INVALID_LITERAL_LIST_PROJECTION: &str = "INVALID_LITERAL_LIST_PROJECTION";
pub const INVALID_NULL_COMPARISON: &str = "INVALID_NULL_COMPARISON";
pub const INVALID_OPTIONAL_MATCH_SCOPE: &str = "INVALID_OPTIONAL_MATCH_SCOPE";
pub const INVALID_OPTIONAL_RELATIONSHIP: &str = "INVALID_OPTIONAL_RELATIONSHIP";
pub const INVALID_PREDICATE_OPERAND: &str = "INVALID_PREDICATE_OPERAND";
pub const INVALID_PRESENCE_PREDICATE: &str = "INVALID_PRESENCE_PREDICATE";
pub const INVALID_SCALAR_EXPRESSION: &str = "INVALID_SCALAR_EXPRESSION";
pub const INVALID_SCALAR_TYPE: &str = "INVALID_SCALAR_TYPE";
pub const INVALID_TYPED_LITERAL_LIST: &str = "INVALID_TYPED_LITERAL_LIST";
pub const INVALID_TYPE_PROJECTION: &str = "INVALID_TYPE_PROJECTION";
pub const INVALID_USAGE_NOTE: &str = "INVALID_USAGE_NOTE";
pub const MANDATORY_RELATIONSHIP_DEPENDS_ON_OPTIONAL_BINDING: &str =
    "MANDATORY_RELATIONSHIP_DEPENDS_ON_OPTIONAL_BINDING";
pub const MAPPED_COLUMN_NOT_FOUND: &str = "MAPPED_COLUMN_NOT_FOUND";
pub const MAPPED_TABLE_NOT_FOUND: &str = "MAPPED_TABLE_NOT_FOUND";
pub const MAPPED_TABLE_REQUIRES_FILTERS: &str = "MAPPED_TABLE_REQUIRES_FILTERS";
pub const MISSING_GRAPHQL_VARIABLE: &str = "MISSING_GRAPHQL_VARIABLE";
pub const MISSING_PARAMETER: &str = "MISSING_PARAMETER";
pub const RELATIONSHIP_ENDPOINT_MISMATCH: &str = "RELATIONSHIP_ENDPOINT_MISMATCH";
pub const UNION_SCHEMA_MISMATCH: &str = "UNION_SCHEMA_MISMATCH";
pub const UNKNOWN_ENDPOINT_LABEL: &str = "UNKNOWN_ENDPOINT_LABEL";
pub const UNKNOWN_NODE_LABEL: &str = "UNKNOWN_NODE_LABEL";
pub const UNKNOWN_PROJECTION: &str = "UNKNOWN_PROJECTION";
pub const UNKNOWN_PROJECTION_ALIAS: &str = "UNKNOWN_PROJECTION_ALIAS";
pub const UNKNOWN_PROPERTY: &str = "UNKNOWN_PROPERTY";
pub const UNKNOWN_RELATIONSHIP_TYPE: &str = "UNKNOWN_RELATIONSHIP_TYPE";
pub const UNKNOWN_VARIABLE: &str = "UNKNOWN_VARIABLE";
pub const UNSORTED_OPTIONAL_RELATIONSHIPS: &str = "UNSORTED_OPTIONAL_RELATIONSHIPS";
pub const UNSUPPORTED_AGGREGATION: &str = "UNSUPPORTED_AGGREGATION";
pub const UNSUPPORTED_COLLECT_SUBQUERY: &str = "UNSUPPORTED_COLLECT_SUBQUERY";
pub const UNSUPPORTED_COUNT_SUBQUERY: &str = "UNSUPPORTED_COUNT_SUBQUERY";
pub const UNSUPPORTED_CYPHER: &str = "UNSUPPORTED_CYPHER";
pub const UNSUPPORTED_DISTINCT_ORDERING: &str = "UNSUPPORTED_DISTINCT_ORDERING";
pub const UNSUPPORTED_EXISTS_PATTERN: &str = "UNSUPPORTED_EXISTS_PATTERN";
pub const UNSUPPORTED_GRAPHQL: &str = "UNSUPPORTED_GRAPHQL";
pub const UNSUPPORTED_GRAPHQL_SCHEMA: &str = "UNSUPPORTED_GRAPHQL_SCHEMA";
pub const UNSUPPORTED_GRAPH_QUERY: &str = "UNSUPPORTED_GRAPH_QUERY";
pub const UNSUPPORTED_OPTIONAL_MATCH_SCOPE: &str = "UNSUPPORTED_OPTIONAL_MATCH_SCOPE";
pub const UNSUPPORTED_OPTIONAL_PREDICATE: &str = "UNSUPPORTED_OPTIONAL_PREDICATE";
pub const UNSUPPORTED_VERSION: &str = "UNSUPPORTED_VERSION";
