import { createTheme } from '@vanilla-extract/css'

import { utils } from '@/styles/utils'
import { paletteDark } from '@/wax/base/palette/palette-dark'
import { fontFamily } from '@/wax/theme/font.css'
import { theme } from '@/wax/theme/theme.css'

export const darkTheme = createTheme(theme, {
  avatarFallback: {
    amber: {
      background: paletteDark.Amber['04'],
      color: paletteDark.Amber['11'],
    },
    blue: {
      background: paletteDark.Blue['04'],
      color: paletteDark.Blue['11'],
    },
    green: {
      background: paletteDark.Green['04'],
      color: paletteDark.Green['11'],
    },
    purple: {
      background: paletteDark.Purple['04'],
      color: paletteDark.Purple['11'],
    },
    red: {
      background: paletteDark.Red['04'],
      color: paletteDark.Red['11'],
    },
  },
  button: {
    bare: {
      hover: paletteDark.GrayAlpha['05'],
    },
    destructive: {
      default: paletteDark.Red['09'],
      focus: paletteDark.Red['10'],
      hover: paletteDark.Red['10'],
    },
    primary: {
      default: paletteDark.PhoebeGreen['09'],
      disabled: paletteDark.GrayAlpha['02'],
      focus: paletteDark.PhoebeGreen['11'],
      hover: paletteDark.PhoebeGreen['12'],
    },
    secondary: {
      default: paletteDark.GrayAlpha['03'],
      focus: paletteDark.GrayAlpha['05'],
      hover: paletteDark.GrayAlpha['05'],
    },
  },
  causeGraph: {
    amber: {
      accent: paletteDark.Amber['10'],
      background: `linear-gradient(${paletteDark.AmberAlpha['02']}, ${paletteDark.AmberAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.AmberAlpha['03']}, ${paletteDark.AmberAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.AmberAlpha['04'],
    },
    blue: {
      accent: paletteDark.Blue['10'],
      background: `linear-gradient(${paletteDark.BlueAlpha['02']}, ${paletteDark.BlueAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.BlueAlpha['03']}, ${paletteDark.BlueAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.BlueAlpha['04'],
    },
    green: {
      accent: paletteDark.Green['10'],
      background: `linear-gradient(${paletteDark.GreenAlpha['02']}, ${paletteDark.GreenAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.GreenAlpha['03']}, ${paletteDark.GreenAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.GreenAlpha['04'],
    },
    orange: {
      accent: paletteDark.Orange['10'],
      background: `linear-gradient(${paletteDark.OrangeAlpha['02']}, ${paletteDark.OrangeAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.OrangeAlpha['03']}, ${paletteDark.OrangeAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.OrangeAlpha['04'],
    },
    purple: {
      accent: paletteDark.Purple['10'],
      background: `linear-gradient(${paletteDark.PurpleAlpha['02']}, ${paletteDark.PurpleAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.PurpleAlpha['03']}, ${paletteDark.PurpleAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.PurpleAlpha['04'],
    },
    red: {
      accent: paletteDark.RedAlpha['10'],
      background: `linear-gradient(${paletteDark.RedAlpha['02']}, ${paletteDark.RedAlpha['02']}), ${paletteDark.Gray['03']}`,
      backgroundHover: `linear-gradient(${paletteDark.RedAlpha['03']}, ${paletteDark.RedAlpha['03']}), ${paletteDark.Gray['03']}`,
      stroke: paletteDark.RedAlpha['04'],
    },
  },
  content: {
    accentContent: {
      primary: paletteDark.PhoebeGreen['12'],
      primaryReverse: paletteDark.PhoebeGreen['02'],
      secondary: paletteDark.PhoebeGreen['11'],
      tertiary: paletteDark.PhoebeGreen['10'],
    },
    code: {
      inlineBackground: paletteDark.GrayAlpha['02'],
      inlineColor: paletteDark.Amber['12'],
    },
    disabled: paletteDark.GrayAlpha['07'],
    error: paletteDark.RedAlpha['10'],
    info: paletteDark.BlueAlpha['10'],
    link: paletteDark.PhoebeGreen['11'],
    linkHover: paletteDark.PhoebeGreen['12'],
    placeholder: paletteDark.GrayAlpha['08'],
    primary: paletteDark.GrayAlpha['12'],
    secondary: paletteDark.GrayAlpha['11'],
    selection: paletteDark.PhoebeGreenAlpha['04'],
    success: paletteDark.GreenAlpha['10'],
    tertiary: paletteDark.GrayAlpha['09'],
    warning: paletteDark.AmberAlpha['11'],
  },
  elevation: {
    e1: `0 4px 24px 0 ${paletteDark.BlackAlpha['03']}, 0 1px 2px 0 ${paletteDark.BlackAlpha['05']}`,
    e2: `0 2px 8px 0 ${paletteDark.BlackAlpha['05']}, 0 1px 2px 0 ${paletteDark.BlackAlpha['05']}`,
    e3: `0 4px 24px 0 ${paletteDark.BlackAlpha['09']}, 0 1px 2px 0 ${paletteDark.BlackAlpha['06']}`,
    e4: `0 32px 96px 0 ${paletteDark.BlackAlpha['10']}, 0 1px 2px 0 ${paletteDark.BlackAlpha['09']}`,
  },
  gradient: {
    card: `linear-gradient(92deg, ${utils.opacify(paletteDark.PhoebeGreenAlpha['01'], 20)} 0%, ${utils.opacify(paletteDark.PhoebeGreenAlpha['07'], 20)} 100%), ${paletteDark.GrayAlpha['02']}`,
  },
  input: {
    stroke: {
      default: paletteDark.GrayAlpha['04'],
      disabled: paletteDark.GrayAlpha['03'],
      focus: paletteDark.PhoebeGreen['11'],
      hover: paletteDark.GrayAlpha['05'],
    },
  },
  pill: {
    amber: {
      background: paletteDark.AmberAlpha['02'],
      backgroundHover: paletteDark.AmberAlpha['03'],
      color: paletteDark.Amber['10'],
      colorHover: paletteDark.Amber['11'],
      stroke: paletteDark.AmberAlpha['06'],
    },
    blue: {
      background: paletteDark.BlueAlpha['02'],
      backgroundHover: paletteDark.BlueAlpha['03'],
      color: paletteDark.Blue['10'],
      colorHover: paletteDark.Blue['10'],
      stroke: paletteDark.BlueAlpha['06'],
    },
    gray: {
      background: paletteDark.GrayAlpha['02'],
      backgroundHover: paletteDark.GrayAlpha['03'],
      color: paletteDark.Gray['11'],
      colorHover: paletteDark.Gray['12'],
      stroke: paletteDark.GrayAlpha['06'],
    },
    graySubtle: {
      background: paletteDark.GrayAlpha['02'],
      backgroundHover: paletteDark.GrayAlpha['03'],
      color: paletteDark.Gray['09'],
      colorHover: paletteDark.Gray['12'],
      stroke: paletteDark.GrayAlpha['06'],
    },
    green: {
      background: paletteDark.GreenAlpha['03'],
      backgroundHover: paletteDark.GreenAlpha['04'],
      color: paletteDark.Green['10'],
      colorHover: paletteDark.Green['11'],
      stroke: paletteDark.GreenAlpha['06'],
    },
    mention: {
      background: paletteDark.PhoebeGreenAlpha['03'],
      backgroundHover: paletteDark.PhoebeGreenAlpha['04'],
      color: paletteDark.PhoebeGreen['11'],
      colorHover: paletteDark.PhoebeGreen['11'],
      stroke: paletteDark.PhoebeGreenAlpha['05'],
    },
    orange: {
      background: paletteDark.OrangeAlpha['02'],
      backgroundHover: paletteDark.OrangeAlpha['03'],
      color: paletteDark.Orange['11'],
      colorHover: paletteDark.Orange['11'],
      stroke: paletteDark.OrangeAlpha['06'],
    },
    purple: {
      background: paletteDark.PurpleAlpha['02'],
      backgroundHover: paletteDark.PurpleAlpha['03'],
      color: paletteDark.Purple['11'],
      colorHover: paletteDark.Purple['11'],
      stroke: paletteDark.PurpleAlpha['06'],
    },
    red: {
      background: paletteDark.RedAlpha['02'],
      backgroundHover: paletteDark.RedAlpha['03'],
      color: paletteDark.Red['10'],
      colorHover: paletteDark.Red['11'],
      stroke: paletteDark.RedAlpha['06'],
    },
  },
  sidebar: {
    button: {
      hover: paletteDark.GrayAlpha['02'],
      selected: paletteDark.GrayAlpha['03'],
    },
    buttonAccent: {
      hover: paletteDark.PhoebeGreenAlpha['02'],
      selected: paletteDark.PhoebeGreenAlpha['03'],
    },
  },
  stroke: {
    floating: paletteDark.Gray['06'],
    focused: paletteDark.PhoebeGreen['11'],
    mainContent: paletteDark.GrayAlpha['02'],
    primary: paletteDark.GrayAlpha['03'],
    secondary: paletteDark.GrayAlpha['02'],
  },
  surface: {
    backdrop: paletteDark.BlackAlpha['08'],
    card: paletteDark.GrayAlpha['02'],
    floating: paletteDark.Gray['04'],
    main: paletteDark.Gray['02'],
    mainContent: paletteDark.Gray['03'],
    onMainContent: paletteDark.GrayAlpha['02'],
    onMainContentHover: paletteDark.GrayAlpha['03'],
    onMainContentSubtle: paletteDark.GrayAlpha['01'],
    skeleton: paletteDark.GrayAlpha['03'],
  },
  switch: {
    default: paletteDark.GrayAlpha['04'],
    hover: paletteDark.GrayAlpha['05'],
    hoverOn: paletteDark.PhoebeGreen['07'],
    on: paletteDark.PhoebeGreen['08'],
  },
  typography: {
    body: {
      fontFamily: fontFamily.inter,
      fontSize: '14px',
      fontWeight: '400',
      letterSpacing: '0.14px',
      lineHeight: '1.65',
    },
    bodyLarge: {
      fontFamily: fontFamily.inter,
      fontSize: '16px',
      fontWeight: '400',
      letterSpacing: '0',
      lineHeight: '1.6',
    },
    bodyLargeStrong: {
      fontFamily: fontFamily.inter,
      fontSize: '16px',
      fontWeight: '500',
      letterSpacing: '0',
      lineHeight: '1.6',
    },
    bodySmall: {
      fontFamily: fontFamily.inter,
      fontSize: '12px',
      fontWeight: '400',
      letterSpacing: '0.12px',
      lineHeight: '1.45',
    },
    bodySmallStrong: {
      fontFamily: fontFamily.inter,
      fontSize: '12px',
      fontWeight: '500',
      letterSpacing: '0.12px',
      lineHeight: '1.45',
    },
    bodyStrong: {
      fontFamily: fontFamily.inter,
      fontSize: '14px',
      fontWeight: '500',
      letterSpacing: '0.14px',
      lineHeight: '1.65',
    },
    buttonStrong: {
      fontFamily: fontFamily.inter,
      fontSize: '14px',
      fontWeight: '500',
      letterSpacing: '0',
      lineHeight: '1.45',
    },
    code: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '14px',
      fontWeight: '400',
      letterSpacing: '0',
      lineHeight: '1.7',
    },
    codeInline: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '14px',
      fontWeight: '400',
      letterSpacing: '0',
      lineHeight: '1.6',
    },
    codeInlineStrong: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '14px',
      fontWeight: '700',
      letterSpacing: '0',
      lineHeight: '1.6',
    },
    codeLarge: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '16px',
      fontWeight: '400',
      letterSpacing: '0',
      lineHeight: '1.7',
    },
    codeSmallInline: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '12px',
      fontWeight: '400',
      letterSpacing: '0',
      lineHeight: '1.55',
    },
    codeSmallInlineStrong: {
      fontFamily: fontFamily.robotoMono,
      fontSize: '12px',
      fontWeight: '700',
      letterSpacing: '0',
      lineHeight: '1.55',
    },
    headingLarge: {
      fontFamily: fontFamily.inter,
      fontSize: '20px',
      fontWeight: '500',
      letterSpacing: '0',
      lineHeight: '1.45',
    },
    headingMedium: {
      fontFamily: fontFamily.inter,
      fontSize: '18px',
      fontWeight: '500',
      letterSpacing: '0',
      lineHeight: '1.45',
    },
    headingSmall: {
      fontFamily: fontFamily.inter,
      fontSize: '16px',
      fontWeight: '500',
      letterSpacing: '0',
      lineHeight: '1.5',
    },
    headingXLarge: {
      fontFamily: fontFamily.inter,
      fontSize: '24px',
      fontWeight: '500',
      letterSpacing: '-0.24px',
      lineHeight: '1.35',
    },
    headingXSmall: {
      fontFamily: fontFamily.inter,
      fontSize: '14px',
      fontWeight: '500',
      letterSpacing: '0.14px',
      lineHeight: '1.45',
    },
  },
})
